### ISSUE TITLE
Browser needs array treatment from #1

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/md5-hex#3]
See #1

Not sure how `md5-o-matic` works, but I am guessing we could just do:

``` js
if (Array.isArray(input)) {
  input = input.join('');
}
```

**Comment by sindresorhus** [comment]
Forgot about the browser thing. Yeah that would work.

**Comment by jamestalmage** [comment]
> that would work

I'm assuming we aren't concerned with supporting Buffers in the browser?

**Comment by sindresorhus** [comment]
Nah
