### ISSUE TITLE
check arguments.length since we now accept an Array

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/md5-hex#4]
I just made this mistake and ended up confused:

``` js
md5Hex(item1, item2);
```

I should have wrapped those args in an array;

``` js
md5Hex([item1, item2]);
```

Do you think we should throw an error if `arguments.length > 1`?

My other thought was iterating over every argument and just adding it to the hash. I'm not sure we could mimic that cleanly in `hasha` though, and I like that the API's are similar now.

**Comment by sindresorhus** [comment]
> Do you think we should throw an error if arguments.length > 1?

Sure, anything to make it less likely for people to do mistakes.

> My other thought was iterating over every argument and just adding it to the hash.

I prefer having only one way to do something in APIs. I also prefer arrays for list type function arguments, which is also more extensible as you haven't wasted all your function arguments. Take this with a grain of salt, but from what I can remember, V8 has a max length of function arguments, so it wouldn't be suitable for really huge lists.
