### ISSUE TITLE
md5 from create-hash is faster than md5-o-matic

### ISSUE THREAD

**Issue by fanatid** [sindresorhus/md5-hex#7]
``` js
var benchmark = require('benchmark')
var createHash = require('create-hash')
var md5 = require('md5-o-matic')

var str = 'the quick brown fox jumps over the lazy dog'

new benchmark.Suite()
  .add('md5-o-matic', function () { md5(str) })
  .add('create-hash', function () { createHash('md5').update(str).digest('hex') })
  .on('cycle', function (event) {
    console.log(String(event.target));
  })
  .run()
```

results:

```
$ node -v
v5.7.1
$ node b.js 
md5-o-matic x 263,501 ops/sec ±0.68% (86 runs sampled)
create-hash x 420,313 ops/sec ±2.79% (77 runs sampled)
```

**Comment by sindresorhus** [comment]
How's the final file size difference? Happy to switch if not too bad. I mainly chose `md5-o-matic` because of its tiny size.

**Comment by fanatid** [comment]
size? check https://github.com/sindresorhus/hasha/issues/9 ;)
I believe it will be pretty small in nearest time https://github.com/crypto-browserify/createHash/issues/11

**Comment by sindresorhus** [comment]
No, I mean, browserified size diff between `md5-o-matic` and `create-hash`.

**Comment by fanatid** [comment]
Right now `create-hash` is 160kB, `md5-o-matic` -- 6kB.

**Comment by sindresorhus** [comment]
That's too much for this use-case.

**Comment by sindresorhus** [comment]
Happy to reconsider when https://github.com/crypto-browserify/createHash/issues/11 is resolved :)

**Comment by fanatid** [comment]
@sindresorhus `md5` is extracted -- https://github.com/crypto-browserify/md5.js
but size is 133kB, because it includes `buffer` and `streams`
want you replace `md5-o-matic` by this?

**Comment by sindresorhus** [comment]
Nah. I don't see much reason to.
